title: "Sally Zheng — MedTech Systems • Biocompatibility • AI"
name: "Sally Zheng"
description: "Systems engineering + biocompatibility across Class I–III & SaMD/SiMD; applying AI where it actually helps."

# if your site is at https://YOUR_USERNAME.github.io/YOUR_REPO
url: "https://YOUR_USERNAME.github.io"
baseurl: "/YOUR_REPO"   # if this is your root (USERNAME.github.io), set this to ""

# pick the color skin: "mint" (sage) or "aqua" (teal)
minimal_mistakes_skin: "mint"

# basic author profile (shows in sidebar/footer)
author:
  name: "Sally Zheng"
  avatar: # e.g., /assets/images/headshot.jpg (add later)
  bio: "Technical lead for Class I–III Medical Devices and SaMD/SiMD; exploring AI applications for accelerating ideas from Bench to Market."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/xzheng2"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your@email.com"

# leave the rest of the file as-is (theme/remote_theme/plugins already set by the starter)
